openapi: 3.0.0
info:
  title: Live Changes API
  description: This
  version: 0.1.0
servers:
  - url: http://your.host.com/v1
    description: This is a test url meant to represent your host. The only valid part in this is the /v1 path
paths:
  /healthcheck:
    get:
      summary: Simple healthcheck endpoint
      description: Returns "connected" if API is up
      responses:
        '200':    # status code
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "connected"
  /threads:
    get:
      summary: Returns info about all thread groups
      description: Returns everything from duration to active threads, etc.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'docs/components/threads.yaml#/AllThreadsResponse'
  /threads/{name}:
    get:
      summary: Get thread group info by name
      description: Retrieves all the information of a thread group by its' name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
               $ref: 'docs/components/threads.yaml#/SingleThreadsResponse'
    post:
      summary: Modify/Update a thread group by its' name
      description: Allows the user to modify a thread group (adjusting duration, adding/removing threads, etc.)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'docs/components/threads.yaml#/ModifyThreadRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'docs/components/thread.yaml#/ModifyThreadResponse'
  /test/status:
    get:
      summary:
      description:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'docs/components/test.yaml#/TestStatus'
  /test/end:
    get:
      summary:
      description:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'docs/components/test.yaml#/TestEnd'
  /test/summary:
    get:
      summary:
      description:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'docs/components/test.yaml#/TestEnd'
  /variables:
    get:
      summary:
      description:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'docs/components/variables.yaml#/GetVariables'
    post:
      summary:
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'docs/components/variables.yaml#/ModifyVariablesReq'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'docs/components/variables.yaml#/ModifyVariablesRes'
  /properties:
    get:
      summary:
      description:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'docs/components/properties.yaml#/GetProperties'
    post:
      summary:
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'docs/components/properties.yaml#/ModifyPropertiesReq'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'docs/components/properties.yaml#/ModifyPropertiesRes'